using System.ComponentModel;

namespace BotCore.Types
{
    public enum SpellBar : short
    {
        [Description("Armachd")]
        arma = 00,
        selfso = 01,
        mesmerize = 02,
        dall = 03,
        portto = 04,
        beagcrahd = 05,
        learning = 06,
        eisd = 07,
        sith = 08,
        puinbeatha = 09,
        hide = 10,
        aite = 11,
        notused = 12,
        creagnert = 13,
        taunt = 14,
        dach = 15,
        bean = 16,
        blindtrap = 17,
        gempolish = 18,
        disarm = 19,
        bre = 20,
        beagiocfein,
        iocfein,
        aobeag,
        aopuin,
        aodall,
        slan = 26,
        beagnochd,
        beagioc,
        ioc,
        morioc = 30,
        ardioc = 31,
        beagcomlha,
        ioccomlha,
        morcomlha,
        poison = 35,
        ardcreag,
        sacrifice,
        meteor,
        massacre,
        srad = 40,
        morsrad = 41,
        ardsrad = 42,
        athar = 43,
        morathar = 44,
        ardathar = 45,
        sal = 46,
        morsal = 47,
        ardsal = 48,
        spion = 49,
        suain = 50,
        aosuain = 51,
        deireas = 52,
        dion = 53,
        reflect = 54,
        mist = 55,
        iteminfo,
        creag,
        morcreag,
        creaggar,
        sradlamh = 60,
        sradmeall = 61,
        sradgar,
        sallamh,
        salmeall,
        salgar,
        atharlamh,
        atharmeall,
        altargar,
        creaglamh,
        creagmeall = 70,
        deosaighead,
        msb,
        msbl,
        msbm,
        mspg,
        iteminfox2,
        nuad,
        ardcomlha,
        aocrahd = 79,
        aomorcrahd = 80,
        aoardcrahd,
        crahd = 82,
        morcrahd = 83,
        ardcrahd = 84,
        aopramh,
        beothaichdeum,
        coffin,
        seun,
        skulled = 89,
        pramh = 90,
        forceshield,
        dash,
        changeele,
        armachd = 94,
        poisonpunch,
        darkspear,
        beagsuain = 97,
        dragonform = 98,
        stonehand = 99,
        disrobe = 100,
        palsy = 101,
        puinspiorad,
        dig,
        dug,
        detechtrap,
        removetrap,
        salvation,
        komet,
        unused,
        unused2 = 110,
        removeds,
        noaffliction = 112,
        lavadragon,
        doubleteam,
        groupbless,
        manaward,
        ghostthing,
        asgall,
        fas = 119,
        gt = 120,
        phoenix,
        wraitht,
        turtleshield,
        catshear = 124,
        howl,
        innerfire = 126,
        handslam,
        godstaff,
        nuadcomlha,
        unholyexp = 130,
        grouphide,
        gravity,
        darkseal = 133,
        bladestorm,
        earthdragon,
        waterdragon,
        flare,
        mforceshield,
        mdeireas,
        mbean = 140,
        harp = 141,
        mindhymn = 142,
        timeslow,
        goodpotion,
        badpotion,
        regen = 146,
        downarrow,
        uparrow,
        magnifi,
        counteratk = 150,
        frostarrow,
        heart,
        keeter,
        torch,
        mermaid,
        groo,
        stonewall,
        formed,
        stararrow = 159,
        fiery,
        shock,
        mudhead,
        tree,
        dragonspirit,
        massarrow,
        siren,
        weed,
        wrap,
        treecut,
        hof = 170,
        feather,
        bats,
        mudwall,
        feather2,
        bats2,
        transform,
        batman,
        bubbleshield,
        threeshot,
        increaseregen = 180,
        greflect,
        jumpto,
        wolfform = 183,
        birdform = 184,
        lizardform = 185,
        fireball,
        rockets,
        coma,
        launch,
        mbeagcrahd = 190,
        mcrahd,
        mmorcrahd,
        mardcrahd,
        mdion,
        maobeagcrahd,
        maocrahd,
        maomorcrahd,
        maoardcrahd,
        mgrpbless,
        maodall = 200,
        maopramh = 201,
        maosuain = 202,
        coffee = 203
    }
}
